import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'fr', 'ar', 'es', 'it'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? frText = '',
    String? arText = '',
    String? esText = '',
    String? itText = '',
  }) =>
      [enText, frText, arText, esText, itText][languageIndex] ?? '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // home
  {
    'z0b1zb7j': {
      'en': 'Welcome back',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'e9tbagyz': {
      'en': 'Find your spot',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'y5c6w11d': {
      'en': 'Vermeg Factory',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'xeo4ctv7': {
      'en': 'Lac 1, Tunis',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '3udc0zsv': {
      'en': 'Navigate',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'hxubxlp1': {
      'en': 'Book Spot',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ue62bzck': {
      'en': 'Maintenance',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '9gwbqon0': {
      'en': 'Upcoming Reminders',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'hvdgi525': {
      'en': 'Insurance Renewal',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '3ntlfgb1': {
      'en': 'Due in 15 days',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'm2p2rc1h': {
      'en': 'Oil Change',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'givotgnm': {
      'en': 'Due in 30 days',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'lno7c14g': {
      'en': 'Parking History',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '70g33wt8': {
      'en': 'Today',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'iwihka9x': {
      'en': 'Parked for 8h 30m',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'q89fcpf8': {
      'en': 'This Week',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '1tr8aarl': {
      'en': '32h 15m total',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'eu37tpie': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // editProfile
  {
    'l4yfucfw': {
      'en': 'Edit Profile',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'sstrmm1r': {
      'en': 'Changes Saved',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'v3fqwp08': {
      'en': 'Your changes have been successfully saved.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'vvbjnfk1': {
      'en': 'First name *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '14z1w7e3': {
      'en': 'Last name *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'gq6oebl4': {
      'en': ' Email *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'mnxuq0ng': {
      'en': 'Phone number *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'mx14zd81': {
      'en': 'Vehicle brand *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'e702cdbf': {
      'en': 'Save changes',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // booking_neuchatel
  {
    'cvbgeu9x': {
      'en': 'Select your spots',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '21jschxk': {
      'en': 'Neuchatel',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'kcozyfys': {
      'en': '1 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '7p7hp5z9': {
      'en': '2',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'y8y9ebvs': {
      'en': '3',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '6h1r8ifn': {
      'en': '4',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'gpheh6qi': {
      'en': '5',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'iwefk9va': {
      'en': '6',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ry9gu419': {
      'en': '7',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'li1bmya7': {
      'en': '8',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'lcclx3kd': {
      'en': '9',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'pqxbkzgl': {
      'en': 'Legend',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '3xety49q': {
      'en': 'Occupied spots',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'dbs3zma3': {
      'en': 'Free spots',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'v9lsif2h': {
      'en': 'You\'ve already booked a spot today !',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'sdpin2m4': {
      'en': 'You can\'t select more than 1 spot for a single day !',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '975zxlwt': {
      'en': 'selected spot',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'xhwc33ya': {
      'en': 'N1 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '2thhbqni': {
      'en': 'N2 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '57fwudzf': {
      'en': 'N3 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '7okgrwan': {
      'en': 'N4 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'x1qmnxjp': {
      'en': 'N5 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'at0xomik': {
      'en': 'N6 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'rf1qsgtd': {
      'en': 'N7 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'bcie74lo': {
      'en': 'N8 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'p9rq0i3e': {
      'en': 'N9',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'hm47hdv2': {
      'en': 'Book now',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ak0m09yg': {
      'en': 'Booking',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // recoverPassword
  {
    'ie4q1ca7': {
      'en': 'Reset Password',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'xb46nyjk': {
      'en':
          'Enter your email address and we\'ll send you instructions to reset your password.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'jht3s5z3': {
      'en': 'Email Address',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'rl9xyhr7': {
      'en': 'Enter your email...',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'j0mm7o5u': {
      'en': 'Enter your email... is required',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'irobfmtb': {
      'en': 'Please enter a valid email address',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '918nx5u8': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'i4na96qt': {
      'en': 'Send Reset Instructions',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // bookingDetails
  {
    'lutgnvca': {
      'en': 'Parking Details',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'engq0fij': {
      'en': 'Parking Location',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'wjjq0t5g': {
      'en': 'Vermeg Factory',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'nq1j7zrp': {
      'en': 'Parking Date',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'wydwv7yk': {
      'en': 'Picked spots',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'h6kob7cw': {
      'en': 'N1 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    't2uz3ntd': {
      'en': 'N2 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'smby9m2h': {
      'en': 'N3 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'h73xivel': {
      'en': 'N4 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '62qxvlfi': {
      'en': 'N5 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'a67b1rrc': {
      'en': 'N6 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'zaprr4sb': {
      'en': 'N7 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '549dhvzp': {
      'en': 'N8 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ah84mbsx': {
      'en': 'N9 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'gut9gpsc': {
      'en': 'C1 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'eb72xlms': {
      'en': 'C2 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ircfunt7': {
      'en': 'C3 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '1mpqq0i3': {
      'en': 'C4 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'nha32ftt': {
      'en': 'C5 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'gxbpg1ky': {
      'en': 'C6 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '9ngshxz9': {
      'en': 'C7 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '722ahh39': {
      'en': 'C8 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'tt1n44pd': {
      'en': 'C9 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '79smrmhl': {
      'en': 'B1 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ef4yn8hp': {
      'en': 'B2 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'iqumdtsf': {
      'en': 'B3 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'engy1a4u': {
      'en': 'B4 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'vzv9iv0t': {
      'en': 'B5 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'o86i5x12': {
      'en': 'B6 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'a037cu8v': {
      'en': 'B7 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'msecy676': {
      'en': 'B8 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'cbw1ypc4': {
      'en': 'B9',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'e4g9tf6b': {
      'en': 'Continue my order',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // checkout
  {
    '3q784spq': {
      'en': 'Checkout',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '4qlh9jcl': {
      'en': 'You are logged in as ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    's9enbihc': {
      'en': 'I agree to the ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'fwr7r5pe': {
      'en': 'Terms & Conditions and Privacy',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ltz7eye1': {
      'en': 'Policy',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'fc3g5i1k': {
      'en': ' of On Spot Vermeg. ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'sfq6q2vr': {
      'en': 'Book',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // settings
  {
    'uccm0oqc': {
      'en': 'Personal info',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'jfy8czb7': {
      'en': 'Edit your profile',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '18craw6m': {
      'en': 'Password',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'arkpcovx': {
      'en': 'My preferences',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '6355v9in': {
      'en': 'Language : English',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'rrnu4ak2': {
      'en': 'Legal information',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'hddab69s': {
      'en': 'Terms and conditions',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'xatys01j': {
      'en': 'Help center and contact',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'h7l2p1ml': {
      'en': 'Cancel reservation',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'i4fb4lo4': {
      'en': 'Log out',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '177opawr': {
      'en': 'Profile',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // signin
  {
    '8l8sk1iw': {
      'en': 'Fill out the information below in order to access your account.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'x7w4fdqy': {
      'en': 'Email *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'txrt7tsw': {
      'en': 'Password *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '4jghz47t': {
      'en': 'Sign In',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'rj610751': {
      'en': 'Or sign in with',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'aje65xlu': {
      'en': 'Email * is required',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '7rxy3iu7': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '9kl6mp2s': {
      'en': 'Password * is required',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'wtxgob5y': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'rbpmu3x2': {
      'en': '         Continue with Google',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'b7regp3t': {
      'en': 'Forgot Password?',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'o2msra5y': {
      'en': 'You do not have an account?',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '0y82rd7s': {
      'en': 'Sign up',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'af8c0kcz': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // signup
  {
    'h7jres5u': {
      'en': 'Fill out the information below in order to access your account.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'jv8uzqgf': {
      'en': 'Email *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'a2giwo1r': {
      'en': 'Password *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ktggnr4p': {
      'en': 'Confirm password *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'zecvtib1': {
      'en': 'Sign Up',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'xcokf1aq': {
      'en': 'Or sign up with',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'pbhmuatj': {
      'en': 'First Name * is required',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ptcybi5h': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '13bqwife': {
      'en': 'Last Name * is required',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'mc95umjs': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ocyfxmb2': {
      'en': 'Phone Number * is required',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'dfg2uha5': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'v53nvece': {
      'en': 'Email * is required',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'wjebi3eb': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'd222wfmy': {
      'en': 'Password * is required',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'iyjtydu0': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '7s0o7lyx': {
      'en': 'Confirm password * is required',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '1lzyckep': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '9xpahiww': {
      'en': '         Continue with Google',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '42a06y7n': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // changePassword
  {
    '1eye5wgp': {
      'en': 'Change Password',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    's5jlokau': {
      'en': 'Changes Saved',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '17pk0ysi': {
      'en': 'Your changes have been successfully saved.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'zbqwy91i': {
      'en':
          'Enter your current password and a new password to update your account security.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '92eee3yr': {
      'en': 'Current password *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'yqcc3qn6': {
      'en': 'New password *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '25fnkjqg': {
      'en': 'Confirm your new password *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'wiht6qr3': {
      'en': 'Save changes',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // terms
  {
    'm6jongvr': {
      'en': 'Terms & Conditions',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '26d6cjow': {
      'en': 'Last Updated: May 17, 2025',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'jsqmzhrc': {
      'en': 'OnSpot Terms of Service',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'rkvk9061': {
      'en':
          'Please read these Terms and Conditions carefully before using the OnSpot application operated by OnSpot Inc.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'p8as2nd3': {
      'en': '1. Acceptance of Terms',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '6hwmsdvy': {
      'en':
          'By accessing or using our service, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the service.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'pct0ozni': {
      'en': '2. Use of Service',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'dpgi7964': {
      'en':
          'OnSpot provides a platform for users to find and reserve parking spaces. Users are responsible for providing accurate information when using the service and must comply with all parking regulations and rules.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'u4wf32cr': {
      'en': '3. User Accounts',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'sl7mz94q': {
      'en':
          'When you create an account with us, you must provide accurate and complete information. You are responsible for safeguarding the password and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'q8dhl204': {
      'en': '4. Cancellation Policy',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'nma34o71': {
      'en':
          'Reservations may be canceled according to the cancellation policy specified at the time of booking. Refunds, if applicable, will be processed according to our refund policy.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'nh5l0z8b': {
      'en': '5. Limitation of Liability',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'f1geodb1': {
      'en':
          'OnSpot shall not be liable for any indirect, incidental, special, consequential or punitive damages resulting from your use or inability to use the service, including but not limited to loss of profits, data, or goodwill.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '3jgnx5a6': {
      'en': '6. Privacy Policy',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'pzmse2e2': {
      'en':
          'Your use of OnSpot is also governed by our Privacy Policy, which is incorporated by reference into these Terms and Conditions.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'tun7j5c7': {
      'en': '7. Changes to Terms',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'fqfow1pg': {
      'en':
          'We reserve the right to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days\' notice prior to any new terms taking effect.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'kvfranpt': {
      'en': '8. Governing Law',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'dvmm7puv': {
      'en':
          'These Terms shall be governed by and construed in accordance with the laws of the United States, without regard to its conflict of law provisions.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'yjqcg3ur': {
      'en': '9. Contact Us',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'l347nn6s': {
      'en':
          'If you have any questions about these Terms, please contact us at support@onspot.com',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // reminders
  {
    '0kafg6xj': {
      'en': 'Car Maintenance',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'gfs438c7': {
      'en': 'Next Service',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'y7oehqfj': {
      'en': 'In 2 weeks',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'l3agnuz1': {
      'en': 'Mileage',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '8ftu3kmr': {
      'en': '45,230 km',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '66fa8gxs': {
      'en': 'Upcoming Reminders',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'dr1g9ojf': {
      'en': 'Insurance Renewal',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'c8zefaa2': {
      'en': 'Due in May 25, 2024',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'u1nmtufe': {
      'en': 'Oil Change',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'qp9watp8': {
      'en': 'Due in 2 weeks - June 8, 2024',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '4jrs16c1': {
      'en': 'Last changed: March 8, 2024',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'lx7vpie9': {
      'en': 'Regular Service',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'gs1us8ln': {
      'en': 'Due in 1 month - June 24, 2024',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '7cs5jjgi': {
      'en': 'Tire Rotation',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'umbnsok4': {
      'en': 'Due in 6 weeks - July 10, 2024',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '95vgvnof': {
      'en': 'Last rotated: January 10, 2024',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'kg40lqeu': {
      'en': 'Completed Tasks',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '25q3trgm': {
      'en': 'Air Filter Replacement',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'q6whnr2f': {
      'en': 'Completed on April 15, 2024',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'aif1smst': {
      'en': 'Next due: October 15, 2024',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'buvzrno9': {
      'en': 'Battery Check',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '17fs7hhk': {
      'en': 'Completed on March 20, 2024',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'nw6xvvvm': {
      'en': 'Next due: September 20, 2024',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'oqsrqdnn': {
      'en': 'Add Reminder',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '3m3n0atz': {
      'en': 'Reminders',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // added_reminder
  {
    '8woim72q': {
      'en': 'Type of service',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'oawz6ft3': {
      'en': 'Search...',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'dqgbsa6c': {
      'en': 'Air Filter Replacement',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'iwvj20x3': {
      'en': 'Battery Check',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'nmukt5rf': {
      'en': 'Insurance renewal',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '7zwi7wlq': {
      'en': 'Oil change ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'tmvcklrd': {
      'en': 'Regular Service',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'oq8wodf4': {
      'en': 'Tire rotation',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'xxjvfrmo': {
      'en': 'Due Date',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '7uu2746d': {
      'en': 'Submit',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ew9czfiu': {
      'en': 'Reminder Details',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'wkzm290w': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // confirmation
  {
    'fp0p6pif': {
      'en': 'Booking Confirmed!',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '3totr275': {
      'en': 'Your parking spot has been successfully reserved.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'xxe7z8rx': {
      'en':
          'We\'ve sent a confirmation email with your parking spot credentials to:',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'yvxrde2h': {
      'en': 'Please present this QR code upon arrival at the parking facility.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'jqkdqsbc': {
      'en': 'Your booking details:',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    's8bphlg4': {
      'en': 'Parking Spot:',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'tv9h1dt3': {
      'en': 'N1 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'tbekw4pq': {
      'en': 'N2 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'zwxn3gn8': {
      'en': 'N3 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'et20yjk7': {
      'en': 'N4 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'imn350da': {
      'en': 'N5 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'oyqsdtdq': {
      'en': 'N6 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    't1jdcs5n': {
      'en': 'N7 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ginaq1kc': {
      'en': 'N8 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '4u1t086q': {
      'en': 'N9 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'e3zurwdf': {
      'en': 'C1 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '76i83k3u': {
      'en': 'C2 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'eked0w0c': {
      'en': 'C3 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'unn9hfye': {
      'en': 'C4 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'xu8hod3p': {
      'en': 'C5 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '96jwxzmp': {
      'en': 'C6 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'yij85gfo': {
      'en': 'C7 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'uj8v2772': {
      'en': 'C8 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'bywj2yw0': {
      'en': 'C9 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'gykn0ghs': {
      'en': 'B1 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '8shfec4f': {
      'en': 'B2 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'dgi3w6ge': {
      'en': 'B3 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '42v9swp8': {
      'en': 'B4 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'aemhfop4': {
      'en': 'B5 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'q1me31tc': {
      'en': 'B6 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'tbzxqrdp': {
      'en': 'B7 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'sqydif08': {
      'en': 'B8 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'vrl796qi': {
      'en': 'B9',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '9dtda4gf': {
      'en': 'Date:',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'fbyny3f9': {
      'en': 'Location:',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'nlhq5yp3': {
      'en': 'Vermeg Neuchatel ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '9gd788jt': {
      'en': 'Vermeg Constance ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '2enq20f2': {
      'en': 'Vermeg Biwa',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '3n76cqmr': {
      'en': 'Booking ID:',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'gv7h6wak': {
      'en': 'Return to Home',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // booking_constance
  {
    '9zl7ffcn': {
      'en': 'Select your spots',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'l0bdsgeb': {
      'en': 'Constance',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '99nwwouz': {
      'en': '1 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '7q5rjhwt': {
      'en': '2',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'est9nwx0': {
      'en': '3',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '1d10yrkp': {
      'en': '4',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'mj33w87h': {
      'en': '5',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ovt4u6g5': {
      'en': '6',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ajn1d0xc': {
      'en': '7',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'iqgfclrz': {
      'en': '8',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'lsarwirp': {
      'en': '9',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '48f40s7g': {
      'en': 'Legend',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'qwijlr7v': {
      'en': 'Occupied spots',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'nnb4myws': {
      'en': 'Free spots',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    't7x6543s': {
      'en': 'You\'ve already booked a spot today !',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '8gzns3mx': {
      'en': 'You can\'t select more than 1 spot for a single day !',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '788acnsy': {
      'en': 'selected spot',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '02hr7due': {
      'en': 'C1 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'yxk8w8qn': {
      'en': 'C2 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'nts8vgkq': {
      'en': 'C3 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'kn8cty40': {
      'en': 'C4 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'p9idk66d': {
      'en': 'C5 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '18f6mpiw': {
      'en': 'C6 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'uhixk2rm': {
      'en': 'C7 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'o7ps3i3m': {
      'en': 'C8 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'y7d75koj': {
      'en': 'C9',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'h1mw3y07': {
      'en': 'Book now',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '646exwdg': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // booking_biwa
  {
    'tpfpjw9u': {
      'en': 'Select your spots',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '70bq876v': {
      'en': 'Biwa',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '62tr9s5c': {
      'en': '1 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ehsy9ecl': {
      'en': '2',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ucn2j9hl': {
      'en': '3',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ujhdkc91': {
      'en': '4',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'kv096t76': {
      'en': '5',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'gj2ukkf8': {
      'en': '6',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'cdvm364e': {
      'en': '7',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'sd97owig': {
      'en': '8',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'pnu6jos3': {
      'en': '9',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'fp12ys2b': {
      'en': 'Legend',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'd7v99jil': {
      'en': 'Occupied spots',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'jfdmlm9c': {
      'en': 'Free spots',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ikhwyr6e': {
      'en': 'You\'ve already booked a spot today !',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '76t0p7sb': {
      'en': 'You can\'t select more than 1 spot for a single day !',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'dkye89kw': {
      'en': 'selected spot',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'psof1e2a': {
      'en': 'B1 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ufvjbwjk': {
      'en': 'B2 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'voe78xd9': {
      'en': 'B3 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '0kk9uxu3': {
      'en': 'B4 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'avzyh2lx': {
      'en': 'B5 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ym233r79': {
      'en': 'B6 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'wyzs8q9i': {
      'en': 'B7 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'u90c1a46': {
      'en': 'B8 ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '0ik448r4': {
      'en': 'B9',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'tnoctaex': {
      'en': 'Book now',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'f4e3irxh': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // user_details
  {
    'wsfhty6h': {
      'en': 'Fill out the information below in order to access your account.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ooavr44v': {
      'en': 'First Name *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'fe3x67ci': {
      'en': 'Last Name *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'bkmi78o2': {
      'en': 'Phone Number *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'm6lwlo8b': {
      'en': 'Vehicle Brand *',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ra9n0f1n': {
      'en': 'Continue',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'rqs6yoeu': {
      'en': 'First Name * is required',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '5ga80lo9': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '5vo3il58': {
      'en': 'Last Name * is required',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'e9wz1bel': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '9r3ucfh0': {
      'en': 'Phone Number * is required',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'bxlijbis': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ixz35gba': {
      'en': 'Email * is required',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'uyf85thv': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'foincadx': {
      'en': 'Password * is required',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'bf8i1i0r': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'xf6vjz1n': {
      'en': 'Confirm password * is required',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'wtj4dq7r': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'u4gnhne7': {
      'en': 'Home',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // welcomePage
  {
    'l3mwe63q': {
      'en': 'Welcome to the app!',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'h5upuf2b': {
      'en': 'Your account has been created successfully.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'iop93sq8': {
      'en': 'Welcome Aboard   ',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '4dsqkgmm': {
      'en':
          'Thank you for joining us! We\'re excited to have you as part of our community. Get ready to explore all the amazing features our app has to offer.',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '8gvzcxs6': {
      'en': 'Go to Homepage',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
  // Miscellaneous
  {
    '9h9ga6wp': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ywtsourz': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '7ryat1g6': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '1mecvps1': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ipxtaf1l': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '5r2zflsf': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '1zlna7zt': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'n32qil71': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '9jrdh327': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '5amohl08': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'a1ehciy7': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'ne3sngl6': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'qmb2q3qn': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'dyg9n3n3': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '1wwiwnwk': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'jjpufmfe': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'mwlrn3e9': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '13fhbkqn': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'brp2m0ou': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'uwprmibw': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'o6cas2jd': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'p86v6vzx': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'aeycpfvt': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    '0dln78ml': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
    'rspl1qva': {
      'en': '',
      'ar': '',
      'es': '',
      'fr': '',
      'it': '',
    },
  },
].reduce((a, b) => a..addAll(b));
